In [ ]:
#syntax
#for var1,var2,var3.. in iterator1,iterator2,iterator3...
for i in range(1,30,2):
    print(i)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29

In [5]:
x=0
for i in range(1,10,3):
     print(i)
     x=x+5
print(x)

1
4
7
15

In [6]:
#multi iterative
for x,y,z in zip(range(10,2,-2),"heyyy",[1,2,3,4]):
         print(x,y,z)

10 h 1
8 e 2
6 y 3
4 y 4

In [7]:
x=[0,2,3,1,2]
y=[1,3,2,0,1]
for i,j in zip(x,y):
    if i>j:
        print(i)
    else:
        print(j)

1
3
3
1
2

In [ ]:
#imagine
#for i in range(1,7):
    #print((7-i)*" ",((i*2)-1)*"*")

In [ ]:
for i in range(1,7):
    print((7-i)*" ",((i*2)-1)*"*")

       *
      ***
     *****
    *******
   *********
  ***********

In [27]:
for i in range(1,7):
    print((7-i)*" ",i*"*")

       *
      **
     ***
    ****
   *****
  ******

In [60]:
print(3*" ",2*"*")

    **

In [ ]:
for i in range(1,7):
    print(30*" ",(7-i)*" ",((i*2)-1)*"*")
for j in range(7,1,-1):
     print(30*" ",(7-j)*" ",((j*2)-1)*"*")

                                      *
                                     ***
                                    *****
                                   *******
                                  *********
                                 ***********
                                *************
                                 ***********
                                  *********
                                   *******
                                    *****
                                     ***

In [49]:
#fibnocci series
#[]
#fill this list with fibnocci series upto 100
#0,1,1,2,3,5,....
x=[]
x.extend([0,1])
while x[-1]+x[-2]<100:
    x.append(x[-1]+x[-2])
print(x)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

In [ ]:
for i in range(1,7):
   print((7-i)*" ",i*"*")

       *
     ***
   *****

In [20]:
x=[]
x.extend([0,1])
while x[-1]+x[-2]<100:
    x.append(x[-1]+x[-2])
print(x)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

In [21]:
x=[1,2,3,4,5,6,7,8,9,10]
x=x[::-1]
for i in x:
    if i%2==0:
        x.remove(i)
print(x)

[9, 7, 5, 3, 1]

In [56]:
nums=[10,20,30]
nums.remove(30)
nums.remove(10)
nums.append(25)
nums.insert(2,30)
nums.insert(1,39)
max(nums)
set(nums)
list(nums)
nums

[20, 39, 25, 30]

In [ ]:

#maximum element in the list
x=[34,52,23,112,213,16]
mx=x[0]
for i in x:
    if i>mx:
        mx=i
print(mx)

213

In [ ]:
#duplicates in the list
x=[1,1,2,2,3,3,4]
y=[]
for i in x:
      if i not in y:
            y.append(i)
print(y)

[1, 2, 3, 4]

In [76]:
#take a list and do the summation of list using 
#inbuilt function
#without using in built function
x=[1,2,3,4,4]
sm=0
for i in x:
    sm=sm+i
print(sm)

14

In [79]:
x="abcde123"
sm=0
for i in x:
    if i.isnumeric():
        sm=sm+int(i)
print(sm)

6

In [93]:
#take a list anf find the largest sequence exist in the list
x = list(set([4,3,6,5,2,5,34,5,35,3,6,9,2,4,7,1,7,3,8,3,11,14,13,17,13,39,360,370,380,400,410,420,430]))
x.sort()
x

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 11,
 13,
 14,
 17,
 34,
 35,
 39,
 360,
 370,
 380,
 400,
 410,
 420,
 430]

In [ ]:
a=x[0]
count=0
y=[]
y.append(a)
for i in x[1::]:
    if i-a==1:
        count=count+1
        a=i
        y.append(a)
    else:
        count=0
        a=i
       
    
print(y)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 13, 14, 17, 34, 35, 39, 360, 370, 380, 400, 410, 420, 430]

In [ ]:
#create a lambda function which will take a single number and return whether it is even or odd
evenodd=lambda a:"even" if a%2==0 else "odd"

In [7]:
def sum(a,b):
    return a+b

In [8]:
sum(10,20)

30

In [3]:
evenodd(29)

'odd'

In [6]:
evenodd(11)

'odd'

In [10]:
sq=lambda a:a**2
sq(8)

64

In [12]:
list(map(lambda a:a**2,[10,20,30,40,50]))

[100, 400, 900, 1600, 2500]

In [23]:
x=[4,1,5,7,2,7,3,7,3,90,12,13]
y=list(map(evenodd,x))
dict(zip(x,y))

{4: 'even',
 1: 'odd',
 5: 'odd',
 7: 'odd',
 2: 'even',
 3: 'odd',
 90: 'even',
 12: 'even',
 13: 'odd'}

In [25]:
x1=[10,20,30,40,50]
x2=[13,19,32,11,55]
#return bigger number from lists
big=lambda a,b :a if a>b else b
list(map(big,x1,x2))

[13, 20, 32, 40, 55]

In [ ]:
x="h18g29b4jh92h"
#filter out all the numbers from string data
ncheck=lambda x:x.isnumeric() 
list(map(ncheck,x))
list(filter(ncheck,x))

['1', '8', '2', '9', '4', '9', '2']

In [72]:
from functools import reduce
reduce(lambda x,y:x+y,[643,23,42,2342])

3050

In [75]:
p=[10,42,5,2,6,2,5,3,6,45,67,56,5,75]
reduce(lambda x,y:x if x>y else y,p)

75

In [81]:
#find the summation of all the numerical even data only
#without using sum function
x="6g393bv348bgg4834b48973b459"
list(filter(ncheck,x))
tr=lambda x:int(x)%2==0
list(filter(tr,list(filter(ncheck,x))))
reduce(lambda x,y:int(x)+int(y),list(filter(tr,list(filter(ncheck,x)))))

50

In [ ]:
#given a list of integers,create a new list where each number is squared
x=[1,2,3,4,5,6,7]
lambda a:a**2
list(map(lambda a:a**2,x))

[1, 4, 9, 16, 25, 36, 49]

In [ ]:
#from a list of numbers,extract only even numbers
list(filter(lambda b:b%2==0, [1,2,3,4,5,6,7]))

[2, 4, 6]

In [ ]:
#given a list of strings,return a list containing

In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.0-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.4.2-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asifs\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\asifs\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   --------------------------- ------------ 6.8/9.9 MB 46.4 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 40.8 MB/s  0:00:00
Downloading numpy-2.4.2-cp314-cp314-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------  12.3/12.4 MB 62.7 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 53.0 MB/s  0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.4.2 pandas-3.0.0 tzdata-2025.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [15]:
#create a data frame 
#even as column and odd as column
#number range would be 1 to 100
a=[]
b=[]
for i in range(1,100):
     if i%2==0:
          a.append(i)
     else:
          b.append(i)
print(a)
print(b)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]

In [28]:
even=lambda x:x%2==0
odd=lambda x:x%2!=0
filter(even,range(1,101))

In [34]:
df=pd.read_csv(r"C:\Users\asifs\Downloads\Match_dataset.csv")
df

,Match_ID,Date,Venue,Team_A,Team_B,Stage,Team_A_Ranking,Team_B_Ranking,Team_A_Form,Team_B_Form,...,HeadToHead_B_Wins,Venue_HomeAdvantage_A,Venue_HomeAdvantage_B,Pitch_Type,Avg_T20_Score_Venue,Toss_Winner,Toss_Decision,Team_A_Tech_Index,Team_B_Tech_Index,Match_Total
0,M0001,2026-03-06,Chennai,New Zealand,Scotland,Super8,5,13,76.97,54.62,...,4,0,0,Spin-Friendly,155,Team_A,Field,251.27,156.37,168
1,M0002,2026-03-07,Mumbai,South Africa,Sri Lanka,Final,6,9,64.19,58.75,...,6,0,0,Flat,175,Team_B,Bat,249.33,187.44,150
2,M0003,2026-03-02,Kolkata,India,PNG,Group,1,20,69.87,45.14,...,0,1,0,Spin-Friendly,165,Team_B,Field,298.24,54.03,160
3,M0004,2026-02-22,Colombo,Netherlands,Ireland,Group,11,12,85.59,61.94,...,4,0,0,Spin-Friendly,160,Team_A,Bat,197.19,174.95,145
4,M0005,2026-02-28,Mumbai,Namibia,South Africa,Group,15,6,45.98,88.52,...,15,0,0,Flat,175,Team_B,Bat,124.91,271.68,185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,M0596,2026-02-12,Kolkata,England,Zimbabwe,Group,3,14,77.24,61.10,...,3,0,0,Spin-Friendly,165,Team_B,Field,294.94,154.29,164
596,M0597,2026-02-14,Colombo,Australia,England,Group,2,3,85.50,78.79,...,8,0,0,Spin-Friendly,160,Team_B,Bat,296.33,278.65,187
597,M0598,2026-02-13,Chennai,Canada,Australia,Group,18,2,36.86,72.24,...,23,0,0,Spin-Friendly,155,Team_A,Bat,70.96,285.08,149
598,M0599,2026-02-21,Delhi,Namibia,Pakistan,Group,15,4,48.37,53.93,...,7,0,0,Pace-Friendly,170,Team_B,Bat,129.25,253.03,197
599,M0600,2026-02-07,Delhi,Netherlands,Canada,Group,11,18,56.36,46.50,...,0,0,0,Pace-Friendly,170,Team_A,Bat,192.85,96.30,187

In [36]:
df=pd.read_excel("https://github.com/singhrau0/Big-Data-Preprocessing/raw/refs/heads/main/Sample%20-%20Superstore.xls")

ImportError: `Import xlrd` failed. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install the xlrd package.

In [ ]:
df

,Match_ID,Date,Venue,Team_A,Team_B,Stage,Team_A_Ranking,Team_B_Ranking,Team_A_Form,Team_B_Form,...,HeadToHead_B_Wins,Venue_HomeAdvantage_A,Venue_HomeAdvantage_B,Pitch_Type,Avg_T20_Score_Venue,Toss_Winner,Toss_Decision,Team_A_Tech_Index,Team_B_Tech_Index,Match_Total
0,M0001,2026-03-06,Chennai,New Zealand,Scotland,Super8,5,13,76.97,54.62,...,4,0,0,Spin-Friendly,155,Team_A,Field,251.27,156.37,168
1,M0002,2026-03-07,Mumbai,South Africa,Sri Lanka,Final,6,9,64.19,58.75,...,6,0,0,Flat,175,Team_B,Bat,249.33,187.44,150
2,M0003,2026-03-02,Kolkata,India,PNG,Group,1,20,69.87,45.14,...,0,1,0,Spin-Friendly,165,Team_B,Field,298.24,54.03,160
3,M0004,2026-02-22,Colombo,Netherlands,Ireland,Group,11,12,85.59,61.94,...,4,0,0,Spin-Friendly,160,Team_A,Bat,197.19,174.95,145
4,M0005,2026-02-28,Mumbai,Namibia,South Africa,Group,15,6,45.98,88.52,...,15,0,0,Flat,175,Team_B,Bat,124.91,271.68,185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,M0596,2026-02-12,Kolkata,England,Zimbabwe,Group,3,14,77.24,61.10,...,3,0,0,Spin-Friendly,165,Team_B,Field,294.94,154.29,164
596,M0597,2026-02-14,Colombo,Australia,England,Group,2,3,85.50,78.79,...,8,0,0,Spin-Friendly,160,Team_B,Bat,296.33,278.65,187
597,M0598,2026-02-13,Chennai,Canada,Australia,Group,18,2,36.86,72.24,...,23,0,0,Spin-Friendly,155,Team_A,Bat,70.96,285.08,149
598,M0599,2026-02-21,Delhi,Namibia,Pakistan,Group,15,4,48.37,53.93,...,7,0,0,Pace-Friendly,170,Team_B,Bat,129.25,253.03,197
599,M0600,2026-02-07,Delhi,Netherlands,Canada,Group,11,18,56.36,46.50,...,0,0,0,Pace-Friendly,170,Team_A,Bat,192.85,96.30,187

In [38]:
df=pd.read_excel("https://github.com/singhrau0/Big-Data-Preprocessing/raw/refs/heads/main/Sample%20-%20Superstore.xls")

ImportError: `Import xlrd` failed. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install the xlrd package.

In [39]:
pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [43]:
df=pd.read_excel("https://github.com/singhrau0/Big-Data-Preprocessing/raw/refs/heads/main/Sample%20-%20Superstore.xls",sheet_name="Orders")
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [45]:
pd.set_option("display.max_columns",None)
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [30]:
df.head()
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [32]:
df.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [31]:
#loc #index name
#iloc #index position
#fetch rows from 6,8,10,12, and all the last five columns in reverse order
df.iloc[6:13:2,-1:-6:-1]
df.loc[6:12:2,"Profit":"Product Name":-1]

KeyError: "Cannot get left slice bound for non-monotonic index with a missing label 'Product Name'. Either sort the index or specify an existing label."

In [59]:
#find out all the bookcases whose profit is greater than500
df[(df["Sub-Category"]=="Bookcases")&(df["Profit"]>500)]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9741,9742,CA-2015-117086,2015-11-08,2015-11-12,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,5408,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.9,5,0.0,1013.127

In [62]:
#find out all corporate data which was lossmaking
df[(df["Segment"]=="Corporate")&(df["Profit"]<0)]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
36,37,CA-2016-117590,2016-12-08,2016-12-10,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,Texas,75080,Central,FUR-FU-10003664,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",190.920,5,0.6,-147.9630
75,76,US-2017-118038,2017-12-09,2017-12-11,First Class,KB-16600,Ken Brennan,Corporate,United States,Houston,Texas,77041,Central,OFF-BI-10004182,Office Supplies,Binders,Economy Binders,1.248,3,0.8,-1.9344
76,77,US-2017-118038,2017-12-09,2017-12-11,First Class,KB-16600,Ken Brennan,Corporate,United States,Houston,Texas,77041,Central,FUR-FU-10000260,Furniture,Furnishings,"6"" Cubicle Wall Clock, Black",9.708,3,0.6,-5.8248
118,119,US-2015-136476,2015-04-05,2015-04-10,Standard Class,GG-14650,Greg Guthrie,Corporate,United States,Bristol,Tennessee,37620,South,OFF-BI-10003650,Office Supplies,Binders,GBC DocuBind 300 Electric Binding Machine,157.794,1,0.7,-115.7156
130,131,US-2017-164147,2017-02-02,2017-02-05,First Class,DW-13585,Dorothy Wardle,Corporate,United States,Columbus,Ohio,43229,East,TEC-PH-10002293,Technology,Phones,Anker 36W 4-Port USB Wall Charger Travel Power...,59.970,5,0.4,-11.9940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9870,9871,CA-2014-114195,2014-11-01,2014-11-03,First Class,EA-14035,Erin Ashbrook,Corporate,United States,Mason,Ohio,45040,East,OFF-BI-10001658,Office Supplies,Binders,GBC Standard Therm-A-Bind Covers,22.428,3,0.7,-17.9424
9912,9913,CA-2015-132388,2015-10-10,2015-10-12,First Class,KN-16390,Katherine Nockton,Corporate,United States,Santa Barbara,California,93101,West,FUR-CH-10001714,Furniture,Chairs,"Global Leather & Oak Executive Chair, Burgundy",362.136,3,0.2,-54.3204
9919,9920,CA-2016-149272,2016-03-15,2016-03-19,Standard Class,MY-18295,Muhammed Yedwab,Corporate,United States,Bryan,Texas,77803,Central,FUR-CH-10000863,Furniture,Chairs,Novimex Swivel Fabric Task Chair,528.430,5,0.3,-143.4310
9920,9921,CA-2016-149272,2016-03-15,2016-03-19,Standard Class,MY-18295,Muhammed Yedwab,Corporate,United States,Bryan,Texas,77803,Central,OFF-BI-10004233,Office Supplies,Binders,"GBC Pre-Punched Binding Paper, Plastic, White,...",22.386,7,0.8,-35.8176
9937,9938,CA-2016-164889,2016-06-03,2016-06-06,Second Class,CP-12340,Christine Phan,Corporate,United States,Los Angeles,California,90049,West,FUR-TA-10001676,Furniture,Tables,Hon 61000 Series Interactive Training Tables,71.088,2,0.2,-1.7772

In [34]:
#find out all order id which does not start with CA
df[~df["Order ID"].str.startswith('CA')]

KeyError: 'Order ID'

In [25]:
#fetch all customer order which starts with RC and  bought Phones
#and we got losses from those customers
df["Customer Id"].str.startswith('CA')

KeyError: 'Customer Id'

In [14]:
df=pd.read_csv("https://github.com/datasciencedojo/datasets/blob/master/titanic.csv")
df

ParserError: Error tokenizing data. C error: Expected 1 fields in line 38, saw 2