In [11]:
import pandas as pd
df=pd.read_excel("https://github.com/singhrau0/Big-Data-Preprocessing/raw/refs/heads/main/Sample%20-%20Superstore.xls",sheet_name="Orders")

In [12]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [13]:
pd.set_option("display.max_columns",None)

In [14]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [15]:
df[['Category','Sales']].groupby('Category').sum()

                       Sales
Category
Furniture        741999.7953
Office Supplies  719047.0320
Technology       836154.0330

In [18]:
#FINDOUT the average profit made by each region in each category
#group by region, category
#profit-average
df[['Category','Region','Profit']].groupby(['Category','Region']).mean()

                            Profit
Category        Region
Furniture       Central  -5.968918
                East      5.068496
                South    20.395199
                West     16.272914
Office Supplies Central   6.244712
                East     23.957114
                South    20.086827
                West     27.733183
Technology      Central  80.231981
                East     88.714084
                South    68.231506
                West     73.962687

In [ ]:
#find out average,minimum,max sales in each region
gt=df[['Region','Sales']].groupby('Region')
gt.mean()
gt.max()
gt.min()

         Sales
Region
Central  0.444
East     0.852
South    1.167
West     0.990

In [29]:
gt.aggregate({'Sales':['min','max','mean']})

         Sales
           min        max        mean
Region
Central  0.444  17499.950  215.772661
East     0.852  11199.968  238.336110
South    1.167  22638.480  241.803645
West     0.990  13999.960  226.493233

In [30]:
#find out average and total sales and avg and max proft for each category in each region
gr=df[['Region','Category','Sales','Profit']].groupby(['Region','Category'])

In [31]:
gr.aggregate({'Sales':['mean','sum'],'Profit':['mean','max']})

                              Sales                  Profit
                               mean          sum       mean        max
Region  Category
Central Furniture        340.534644  163797.1638  -5.968918   770.3520
        Office Supplies  117.458801  167026.4150   6.244712  4946.3700
        Technology       405.753124  170416.3120  80.231981  8399.9760
East    Furniture        346.574383  208291.2040   5.068496  1013.1270
        Office Supplies  120.044425  205516.0550  23.957114  1453.1238
        Technology       495.278469  264973.9810  88.714084  5039.9856
South   Furniture        353.309289  117298.6840  20.395199   746.4078
        Office Supplies  126.282727  125651.3130  20.086827  3177.4750
        Technology       507.753952  148771.9080  68.231506  2799.9840
West    Furniture        357.302325  252612.7435  16.272914   629.0100
        Office Supplies  116.422377  220853.2490  27.733183  1906.4850
        Technology       420.687533  251991.8320  73.962687  6719.9808

In [47]:
#find out top2 subcategory based on total profit made in each region
gr=df[['Region','Sub-Category','Profit']].groupby(['Region','Sub-Category'])

In [48]:
gr.sum()

                          Profit
Region  Sub-Category
Central Accessories    7251.6306
        Appliances    -2638.6175
        Art            1195.1591
        Binders       -1043.6369
        Bookcases     -1997.9043
...                          ...
West    Paper         12119.2364
        Phones         9110.7426
        Storage        8645.3222
        Supplies        626.0465
        Tables         1482.6073

[68 rows x 1 columns]

In [50]:
grnew=gr.sum().sort_values(by=['Region','Profit'],ascending=False)

In [51]:
grnew

                          Profit
Region  Sub-Category
West    Copiers       19327.2351
        Accessories   16484.5983
        Binders       16096.8016
        Paper         12119.2364
        Phones         9110.7426
...                          ...
Central Machines      -1486.0666
        Bookcases     -1997.9043
        Appliances    -2638.6175
        Tables        -3559.6504
        Furnishings   -3906.2168

[68 rows x 1 columns]

In [54]:
grnew.groupby('Region').head(2)

                          Profit
Region  Sub-Category
West    Copiers       19327.2351
        Accessories   16484.5983
South   Phones        10767.2753
        Accessories    7004.5424
East    Copiers       17022.8418
        Phones        12314.6860
Central Copiers       15608.8413
        Phones        12323.0267

In [103]:
#find out least profitable subcategory in each year 
import datetime as dt
df['Year']=pd.to_datetime(df['Order Date']).dt.year

In [97]:
grnew=df[['Year','Sub-Category','Profit']].groupby(['Year','Sub-Category'])

In [100]:
grnew.sum().sort_values(by=['Year','Profit'],ascending=False)

                       Profit
Year Sub-Category
1970 Copiers       55617.8249
     Phones        44515.7306
     Accessories   41936.6357
     Paper         34053.5693
     Binders       30221.7633
     Chairs        26590.1663
     Storage       21278.8264
     Appliances    18138.0054
     Furnishings   13059.1436
     Envelopes      6964.1767
     Art            6527.7870
     Labels         5546.2540
     Machines       3384.7569
     Fasteners       949.5182
     Supplies      -1189.0995
     Bookcases     -3472.5560
     Tables       -17725.4811

In [101]:
# pivot_table
# find out of total sales and minimum sale,total profit and average discount for each category in each year
df.pivot_table(index=['Year','Category'],values=['Sales','Profit','Discount'],aggfunc={'Sales':['sum','min'],'Profit':['sum'],'Discount':['mean']})

                      Discount       Profit  Sales
                          mean          sum    min          sum
Year Category
1970 Furniture        0.173923   18451.2728  1.892  741999.7953
     Office Supplies  0.157285  122490.8008  0.444  719047.0320
     Technology       0.132323  145454.9481  0.990  836154.0330

In [ ]:
import datetime as

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year
0,1,CA-2016-152156,2016,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,1970
1,2,CA-2016-152156,2016,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,1970
2,3,CA-2016-138688,2016,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,1970
3,4,US-2015-108966,2015,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,1970
4,5,US-2015-108966,2015,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,1970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,1970
9990,9991,CA-2017-121258,2017,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,1970
9991,9992,CA-2017-121258,2017,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,1970
9992,9993,CA-2017-121258,2017,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,1970
9993,9994,CA-2017-119914,2017,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,1970

0      1970
1      1970
2      1970
3      1970
4      1970
5      1970
6      1970
7      1970
8      1970
9      1970
10     1970
11     1970
12     1970
13     1970
14     1970
16     1970
18     1970
23     1970
26     1970
27     1970
29     1970
30     1970
34     1970
37     1970
44     1970
50     1970
53     1970
113    1970
138    1970
165    1970
178    1970
215    1970
335    1970
392    1970
Name: Year, dtype: int32

In [91]:
# pivot_table
# find out of total sales and minimum sale,total profit and average discount for each category in each year
df.pivot_table(index=['Year','Category'],values=['Sales','Profit','Discount'],aggfunc={'Sales':['sum','min'],'Profit':['sum'],'Discount':['mean']})

                      Discount       Profit  Sales
                          mean          sum    min          sum
Year Category
1970 Furniture        0.173923   18451.2728  1.892  741999.7953
     Office Supplies  0.157285  122490.8008  0.444  719047.0320
     Technology       0.132323  145454.9481  0.990  836154.0330