In [11]:
import pandas as pd
df=pd.read_excel("https://github.com/singhrau0/Big-Data-Preprocessing/raw/refs/heads/main/Sample%20-%20Superstore.xls",sheet_name="Orders")

In [12]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [13]:
pd.set_option("display.max_columns",None)

In [14]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [15]:
df[['Category','Sales']].groupby('Category').sum()

                       Sales
Category
Furniture        741999.7953
Office Supplies  719047.0320
Technology       836154.0330

In [18]:
#FINDOUT the average profit made by each region in each category
#group by region, category
#profit-average
df[['Category','Region','Profit']].groupby(['Category','Region']).mean()

                            Profit
Category        Region
Furniture       Central  -5.968918
                East      5.068496
                South    20.395199
                West     16.272914
Office Supplies Central   6.244712
                East     23.957114
                South    20.086827
                West     27.733183
Technology      Central  80.231981
                East     88.714084
                South    68.231506
                West     73.962687

In [ ]:
#find out average,minimum,max sales in each region
gt=df[['Region','Sales']].groupby('Region')
gt.mean()
gt.max()
gt.min()

         Sales
Region
Central  0.444
East     0.852
South    1.167
West     0.990

In [29]:
gt.aggregate({'Sales':['min','max','mean']})

         Sales
           min        max        mean
Region
Central  0.444  17499.950  215.772661
East     0.852  11199.968  238.336110
South    1.167  22638.480  241.803645
West     0.990  13999.960  226.493233

In [30]:
#find out average and total sales and avg and max proft for each category in each region
gr=df[['Region','Category','Sales','Profit']].groupby(['Region','Category'])

In [31]:
gr.aggregate({'Sales':['mean','sum'],'Profit':['mean','max']})

                              Sales                  Profit
                               mean          sum       mean        max
Region  Category
Central Furniture        340.534644  163797.1638  -5.968918   770.3520
        Office Supplies  117.458801  167026.4150   6.244712  4946.3700
        Technology       405.753124  170416.3120  80.231981  8399.9760
East    Furniture        346.574383  208291.2040   5.068496  1013.1270
        Office Supplies  120.044425  205516.0550  23.957114  1453.1238
        Technology       495.278469  264973.9810  88.714084  5039.9856
South   Furniture        353.309289  117298.6840  20.395199   746.4078
        Office Supplies  126.282727  125651.3130  20.086827  3177.4750
        Technology       507.753952  148771.9080  68.231506  2799.9840
West    Furniture        357.302325  252612.7435  16.272914   629.0100
        Office Supplies  116.422377  220853.2490  27.733183  1906.4850
        Technology       420.687533  251991.8320  73.962687  6719.9808

In [47]:
#find out top2 subcategory based on total profit made in each region
gr=df[['Region','Sub-Category','Profit']].groupby(['Region','Sub-Category'])

In [48]:
gr.sum()

                          Profit
Region  Sub-Category
Central Accessories    7251.6306
        Appliances    -2638.6175
        Art            1195.1591
        Binders       -1043.6369
        Bookcases     -1997.9043
...                          ...
West    Paper         12119.2364
        Phones         9110.7426
        Storage        8645.3222
        Supplies        626.0465
        Tables         1482.6073

[68 rows x 1 columns]

In [50]:
grnew=gr.sum().sort_values(by=['Region','Profit'],ascending=False)

In [51]:
grnew

                          Profit
Region  Sub-Category
West    Copiers       19327.2351
        Accessories   16484.5983
        Binders       16096.8016
        Paper         12119.2364
        Phones         9110.7426
...                          ...
Central Machines      -1486.0666
        Bookcases     -1997.9043
        Appliances    -2638.6175
        Tables        -3559.6504
        Furnishings   -3906.2168

[68 rows x 1 columns]

In [54]:
grnew.groupby('Region').head(2)

                          Profit
Region  Sub-Category
West    Copiers       19327.2351
        Accessories   16484.5983
South   Phones        10767.2753
        Accessories    7004.5424
East    Copiers       17022.8418
        Phones        12314.6860
Central Copiers       15608.8413
        Phones        12323.0267

In [14]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [15]:
import datetime as dt

In [16]:
df['Year']=df['Order Date'].dt.year

In [17]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,2014
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,2017
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,2017
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,2017
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,2017

In [19]:
#find out least profitable Sub-category in each year
gr=df[['Year','Sub-Category','Profit']].groupby(['Year','Sub-Category'])

In [21]:
gr_new=gr.sum().sort_values(by=['Year','Profit'],ascending=True)

In [22]:
gr_new.groupby('Year').head(2)

                      Profit
Year Sub-Category
2014 Tables       -3124.0427
     Bookcases     -346.1707
2015 Tables       -3509.8019
     Bookcases    -2755.2302
2016 Tables       -2950.9418
     Supplies      -698.9639
2017 Tables       -8140.6947
     Machines     -2869.2156

In [24]:
# pivot_table
# find out of total sales and minimum sale,total profit and average discount for each category in each year
df.pivot_table(index=['Year','Category'],values=['Sales','Profit','Discount'],aggfunc={'Sales':['sum','min'],'Profit':['sum'],'Discount':['mean']})

                      Discount      Profit  Sales
                          mean         sum    min          sum
Year Category
2014 Furniture        0.182090   5457.7255  3.480  157192.8531
     Office Supplies  0.156368  22593.4161  0.852  151776.4120
     Technology       0.136620  21492.8325  1.980  175278.2330
2015 Furniture        0.168783   3015.2029  2.960  170518.2370
     Office Supplies  0.160274  25099.5338  0.984  137233.4630
     Technology       0.126895  33503.8670  2.376  162780.8090
2016 Furniture        0.176904   6959.9531  2.328  198901.4360
     Office Supplies  0.152107  35061.2292  0.836  183939.9820
     Technology       0.136601  39773.9920  1.980  226364.1800
2017 Furniture        0.169854   3018.3913  1.892  215387.2692
     Office Supplies  0.160040  39736.6217  0.444  246097.1750
     Technology       0.130288  50684.2566  0.990  271730.8110

In [ ]:
#find out avg and minimun discount,total profit and total sales made in each month for each category

In [26]:
df['Month']=df['Order Date'].dt.month

In [27]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Month
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,2014,1
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,2017,2
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,2017,2
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,2017,2
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,2017,5

In [30]:
#find out avg and minimun discount,total profit and total sales made in each month for each category
df.pivot_table(index=['Month','Category'],values=['Profit','Discount','Sales'],aggfunc={'Profit':['sum'],'Discount':['mean','min'],'Sales':['sum']})

                       Discount           Profit        Sales
                           mean  min         sum          sum
Month Category
1     Furniture        0.157037  0.0  -1944.2130   31569.2416
      Office Supplies  0.144493  0.0   6243.7654   33233.8310
      Technology       0.158904  0.0   4834.8937   30121.7630
2     Furniture        0.178889  0.0    693.5796   15765.9204
      Office Supplies  0.148023  0.0   4274.0190   20641.9130
      Technology       0.106667  0.0   5327.0121   23343.4180
3     Furniture        0.182143  0.0    771.9875   50768.2758
      Office Supplies  0.149034  0.0  10455.6295   56385.6430
      Technology       0.145775  0.0  17367.0702   97851.5700
4     Furniture        0.163551  0.0   1460.3261   40698.5836
      Office Supplies  0.171599  0.0   4747.6876   49433.2700
      Technology       0.130631  0.0   5379.4226   47630.2750
5     Furniture        0.187267  0.0   2302.2981   48365.1307
      Office Supplies  0.167627  0.0   9030.0467   43021.5260
      Technology       0.133582  0.0  11078.9630   63642.1550
6     Furniture        0.191310  0.0    982.3847   52999.4633
      Office Supplies  0.162980  0.0  11073.2905   51414.6330
      Technology       0.130233  0.0   9230.1202   48304.5830
7     Furniture        0.166463  0.0   1412.6846   49377.0120
      Office Supplies  0.163680  0.0   2319.0104   43007.0590
      Technology       0.129323  0.0  10100.9698   54854.0260
8     Furniture        0.183790  0.0      4.0941   44884.0450
      Office Supplies  0.157206  0.0  12673.4033   62134.1620
      Technology       0.116031  0.0   9099.4410   52025.8560
9     Furniture        0.154468  0.0   5460.0023  106380.5907
      Office Supplies  0.153988  0.0  17299.2094  101888.6460
      Technology       0.124153  0.0  14098.2636   99380.7090
10    Furniture        0.190749  0.0  -3027.9321   58087.5157
      Office Supplies  0.160211  0.0  10929.4082   55203.5240
      Technology       0.136306  0.0  23882.5652   87031.9450
11    Furniture        0.171379  0.0   3920.0007  121286.0490
      Office Supplies  0.161227  0.0  15508.0128  100040.1810
      Technology       0.135069  0.0  16040.4130  131134.8410
12    Furniture        0.173811  0.0   6416.0602  121817.9675
      Office Supplies  0.145466  0.0  17937.3180  102642.6440
      Technology       0.136364  0.0  19015.8137  100832.8920

In [ ]:
#what are the highest revenue generating Subcategory in year 2015

NameError: name 'plt' is not defined